feat: 룸 만들기, 룸 수정하기 모달 추가
memochat/memochat-client pull request #16
Opened 2022-08-02 16:07 UTC by syoung125

## 📍 주요 변경사항

- ModalLayout, Modal 컴포넌트 이전
- 룸 만들기, 룸 수정하기 모달 추가
-  modalProps onClose 타입 수정
- purple6 색상 추가
<img width="365" alt="image" src="https://user-images.githubusercontent.com/39763891/182421391-e4161295-86b3-4114-adef-7873fd3a7b25.png">
(룸 유형 선택했을 때 색상이 purple6 더라구요..!)

## 🔗 참고자료

## 💡 중점적으로 봐주었으면 하는 부분

2022-08-04 13:35 UTC, sooohka requested changes

2022-08-04 13:35 UTC, sooohka commented on src/components/reusable/ModalLayout/ModalLayout.tsx
> +    open && !isVisible && setIsVisible(true);
isVisible을 디펜던시로 가지는 useEffect내부에서 setIsVisble을 호출하면 불필요한 useEffect 호출이 한번 더 발생할것 같아요
결국엔 open이 True면 isvisible이 true가 되는 로직같은데
```open && setIsVIsible(true)``` 로 바꾸는건 어떤가요

2022-08-04 13:35 UTC, sooohka commented on src/components/reusable/ModalLayout/ModalLayout.tsx
> +  }, [open, isVisible]);
위 내용과 동일합니다!

2022-08-04 13:35 UTC, sooohka commented on src/components/reusable/room/UpsertRoomDialog/UpsertRoomDialog.tsx
> +    setValue({
setValue에서 value값을 참조하신것 같은데 이 value값이 항상 직전값임을 보장할 수 없어서 setvalue인자에 인자를 함수형 ```setValue(prev=>({...prev,roomTypeId: id}))```으로 넣는게 더 좋을것 같습니다!!

2022-08-06 14:43 UTC, syoung125 commented on src/components/reusable/ModalLayout/ModalLayout.tsx
> +    open && !isVisible && setIsVisible(true);
전에 코드 작성 시 이렇게 작성하지 않으면 제대로 동작이 안되는 부분이 있었던 것 같은데, 다시보니까 isVisible이 없어도 잘 되네요!
반영했습니다👍 (이전코드를 그대로 옮기면서 이렇게 된 것 같네요ㅜㅜ)
[362a9d4](https://github.com/memochat/memochat-client/pull/16/commits/362a9d4faaf486f276cc2a0431aacba63d67a48a)

2022-08-06 14:43 UTC, syoung125 commented on src/components/reusable/room/UpsertRoomDialog/UpsertRoomDialog.tsx
> +    setValue({
[362a9d4](https://github.com/memochat/memochat-client/pull/16/commits/362a9d4faaf486f276cc2a0431aacba63d67a48a)

2022-08-07 04:38 UTC, sooohka approved these changes

2022-08-07 14:29 UTC, merged