feat: 룸 설정페이지
memochat/memochat-client pull request #17
Opened 2022-08-06 04:54 UTC by sooohka

## 📍 주요 변경사항
 - 룸 설정 페이지 작업

<img width="376" alt="image" src="https://user-images.githubusercontent.com/67774824/183234507-124b2e4a-dee0-4043-83ec-fabe66899ab6.png">

## 🔗 참고자료

## 💡 중점적으로 봐주었으면 하는 부분

2022-08-06 16:45 UTC, syoung125 requested changes

2022-08-06 16:45 UTC, syoung125 commented on src/components/roomDetail/RoomDetail/RoomDetail.stories.tsx
> +  component: RoomDetail,
스토리북에 타이틀을 넣어주는 것이 좋을 것 같아요
타이틀이 없어서 그런가 띄어쓰기가 추가되고, 다른 컴포넌트에 비해 폴더 깊이가 깊어진것 같네여
<img width="215" alt="image" src="https://user-images.githubusercontent.com/39763891/183256678-6028cf26-9cfc-40a9-b60e-9e60b0e92247.png">

2022-08-06 16:45 UTC, syoung125 commented on src/components/roomDetail/RoomDetail/RoomDetail.styles.ts
> +export const NBCTitle = styled.h3`
NBC가 무엇의 약자인가요??

2022-08-06 16:45 UTC, syoung125 commented on src/components/roomDetail/RoomDetail/RoomDetail.tsx
> +      </S.Header>
헤더는 shared 컴포넌트로 재사용하는 것이 좋을 것같아요!
이 pr 과는 무관한 것 같아서 우선 여기 todo 로 작성해두고 다음에 추가하면 좋을 것 같습니다~

2022-08-06 16:45 UTC, syoung125 commented on src/components/roomDetail/RoomSection/RoomSection.tsx
> +const RoomSection = (props: RoomSectionProps) => {
RoomSection은 채팅룸의 섹션??이라고 생각할수도 있을 것같아서 RoomDetailSection이라던지 좀더 구체적인 네이밍으로 변경하면 좋을 것같아요!

2022-08-06 16:45 UTC, syoung125 commented on src/components/roomDetail/RoomSection/RoomSection.tsx
> +      )}
섹션 content에 링크, 리마인더 등이 추가되면 이부분에 다양한 ui가 추가될 가능성이 있을 것같아요.
그래서 확장성 측면에서 RoomSection의 content는 children으로 받는 것이 더 좋아보여요ㅠ

2022-08-06 16:45 UTC, syoung125 commented on src/components/roomDetail/RoomSection/RoomSection.tsx
> +      )}
1. 이미지 박스로 이미지를 한번더 감싸신 이유가 있나요?? 이미지에 직접 스타일을 줄수 있을 것같아서요!
2. 이미지에 `object-fit: cover;` 을 주면 이미지가 수축, 늘어남 없이 확대되어 꽉차게 보여서 이 속성 추가해주는 것이 좋을 것같아요! (모든 이미지가 정사각형은 아니라 직사각형인 경우 수축될 것 같아서요)
3. 이미지 섹션 반응형 대응:  grid 레이아웃을 사용해서 `grid-template-columns: repeat(4, 1fr)`이렇게 화면너비가 어떻든 최대 4개까지 보여주는 것도 좋을 것같아요!  이미지 너비는 100%로 만들고 이미지에 `aspect-ratio: 1 / 1;` 속성 추가하면 비율도 정방형으로 유지할 수 있습니다

![Aug-07-2022 01-30-52](https://user-images.githubusercontent.com/39763891/183257738-79f2596f-5678-4aed-813d-4d2fa7c6ebed.gif)

2022-08-06 16:45 UTC, syoung125 commented on src/components/roomDetail/RoomSection/RoomSection.types.ts
> +  color?: keyof ColorTheme;
확인해보니 이 color는 섹션의 색이 아닌 색션 타이틀의 색상이라서 titleColor가 되어야 더 명확할 것같아요! 

(또는 시멘틱한 방법으로 주의해야하는 메뉴만 색상이 빨간색이니까 type을 'default' | 'danger' (또는 'warning') 이런식으로 줘서 danger 타입인 경우 타이틀 색상을 빨간색으로 줘도 좋을 것같아요)

2022-08-06 16:45 UTC, syoung125 commented on src/pages/rooms/[id]/detail.tsx
> +  }
throw를 하기때문에 try catch와 같은 안전장치가 필요할 것같아요
또는 에러는 로깅정도만 하고 잘못된 페이지 접근인 경우 홈이나 이전페이지로 리다이렉션 시켜주거나 하는 방향은 어떤가요?

2022-08-06 16:45 UTC, syoung125 commented on src/components/roomDetail/RoomSection/RoomSection.tsx
> +const RoomSection = (props: RoomSectionProps) => {
ui를 보면 섹션보다는 누를 수 있는 버튼에 가까운 것같기도 해요! RoomDetailMenu? RoomDetailMenuItem도 괜찮은 것같은데 어떻게 생각하시나요??

<img width="408" alt="image" src="https://user-images.githubusercontent.com/39763891/183258171-ac477349-2b47-4f0c-aa6d-5ed784ba8da9.png">

'메모룸 나가기'는 사실 섹션이라기보다 버튼의 역할만 하는것같아서 컴포넌트 명이 섹션인 경우 코드로만 위 ui를 추측하기 어려울 것 같아요ㅠㅠ

2022-08-07 06:40 UTC, sooohka commented on src/components/reusable/Icon/Icon.tsx
> +  return <StyledSvgIcon {...props} colorname={colorName} />;
https://github.com/memochat/memochat-client/pull/18#discussion_r939549844

2022-08-07 06:45 UTC, sooohka commented on src/components/roomDetail/RoomDetail/RoomDetail.styles.ts
> +export const NBCTitle = styled.h3`
나와의 번개챗.. 입니다 ㅋㅋ;
당시에 어떤이름으로 할지 생각이 안나서 임시로 저렇게 뒀었는데 수정하는걸 깜빡헀네요
수정하겠습니다~

2022-08-07 06:56 UTC, sooohka commented on src/components/roomDetail/RoomSection/RoomSection.tsx
> +const RoomSection = (props: RoomSectionProps) => {
확실히 네이밍이 헷갈리는 부분이 있네요
RoomDetailMenu로 변경하겠습니다 ㅎㅎ

2022-08-07 07:26 UTC, sooohka commented on src/components/roomDetail/RoomSection/RoomSection.tsx
> +      )}
> 

1.  Next/image 컴포넌트를 사용하였는데 next/image컴포넌트에 스타일을 전달하려고 이렇게 진행했습니다!
2. 몰랐던부분인데 좋네용 ㅎㅎ 반영했습니다~
3. Next/image를 사용하면 image컴포넌트 상위에 span태그가 있어서 이부분이 잘 안되는것 같네요 ㅜㅜ Next/image를 제거하던가 다른방법을 찾아봐야 될것 같네요. 일단은 Next/image에 고정너비로 채우긴 했는데 추후에 바꿔보던가 하면 좋을것 같아요

2022-08-07 07:32 UTC, sooohka commented on src/components/roomDetail/RoomSection/RoomSection.types.ts
> +  color?: keyof ColorTheme;
전에 variant를 사용하기로 했던것 같아 variant "default"|"danger"속성을 추가해 시멘틱하게 적용했습니다~

2022-08-07 07:48 UTC, sooohka commented on src/pages/rooms/[id]/detail.tsx
> +  }
우선 이걸 추가한 이유가 ctx.query이 type값이 string | string[]를 받는데 페이지 컴포넌트 props 체킹할때 id값으로 string만 허용하기 때문에 typeError가 걸려서 추가한거긴 해요. 하지만 저희가 다이나믹 라우트의 key값을 [id]로 설정했기 때문에 id는 항상 string이라 이 코드는 발생할 가능성이 없는 코드입니다. 그래서 try catch로 감싸는게 불필요할것 같아요 ㅜㅜ
다만 throw하는게  확실히 불안해 보이긴 한것 같아 throw 문을 지우고 as typecasing으로 id를 넘기는 쪽으로 해보겠습니다.

2022-08-07 14:59 UTC, syoung125 commented on src/pages/rooms/[id]/detail.tsx
> +      id: id as string,
```suggestion
  return {
    props: {
      id: String(id),
```

또는 `id.toString()`으로 형변환 해주면 에러안날 것 같은데 시도해봐주실수 있나요??

2022-08-07 16:01 UTC, syoung125 commented on src/components/roomDetail/RoomSection/RoomSection.tsx
> +      )}
3. next/image 스타일 적용 잘 안되는 부분 수정해보았는데 확인 부탁드려요! ([ad8ac3e](https://github.com/memochat/memochat-client/pull/17/commits/ad8ac3e062a8b34257820ddd69d8cab004345395))

[스토리북](https://62b83eaee7b099045d81e168-nhewovsobm.chromatic.com/?path=/story/components-roomdetail-roomdetail--default)

2022-08-07 16:04 UTC, syoung125 commented on src/components/roomDetail/RoomDetail/RoomDetail.tsx
> +        </S.RoomBaseInfo>
이부분이 룸 정보 변경을 위한 부분이기도 하지만 사용자에게 룸 정보를 보여주는 부분이기도 해서 Change로 한정짓기에 애매한 것 같아보여요! 혹시 이렇게 네이밍 변경하는 것은 어떤가요??

2022-08-07 16:04 UTC, syoung125 commented on src/components/roomDetail/RoomDetailMenu/RomDetailMenu.tsx
> -            <Icon name="ArrowRight" width="16px" height="16px"></Icon>
children이 없는 경우
```
<Icon name="ArrowRight" width="16px" height="16px"></Icon>
```
코드 보다
```
<Icon name="ArrowRight" width="16px" height="16px" />
```
이렇게 사용하는 것이 더 깔끔해보여서 변경했어요~!

2022-08-07 16:08 UTC, syoung125 approved these changes

2022-08-08 14:18 UTC, sooohka commented on src/components/roomDetail/RoomSection/RoomSection.tsx
> +      )}
> 3. next/image 스타일 적용 잘 안되는 부분 수정해보았는데 확인 부탁드려요! ([ad8ac3e](https://github.com/memochat/memochat-client/pull/17/commits/ad8ac3e062a8b34257820ddd69d8cab004345395))
> 
> [스토리북](https://62b83eaee7b099045d81e168-nhewovsobm.chromatic.com/?path=/story/components-roomdetail-roomdetail--default)

크으 이런식으로 해결할 수 있네요 ㅎㅎ 감사합니다!!

2022-08-08 14:22 UTC, sooohka commented on src/pages/rooms/[id]/detail.tsx
> +      id: id as string,
오 배열도 toString메서드가 있는지 처음 알았네요 ㅎㅎ.
아 그리고 형변환 되는것 같습니다!! 형변환으로 적용해보겠습니다

2022-08-08 14:27 UTC, sooohka commented on src/components/roomDetail/RoomDetailMenu/RomDetailMenu.tsx
> -            <Icon name="ArrowRight" width="16px" height="16px"></Icon>
오 좋습니다!! 
추가로 코드 일관성을 위해서 관련 lint룰을 추가하면 좋을것 같아서 추가했습니다~
```"react/self-closing-comp": "warn"```

2022-08-08 14:38 UTC, merged