✨ feat Room 메모 작성폼
memochat/memochat-client pull request #18
Opened 2022-08-06 07:52 UTC by sooohka

## 📍 주요 변경사항
- room memo form 작성
- Dom 에러가 발생해 Icon 컴포넌트 props colorName -> colorname으로 변경

<img width="392" alt="image" src="https://user-images.githubusercontent.com/67774824/183240006-dd26afac-f764-46fb-b5f8-9d9cd2a9a266.png">

## 🔗 참고자료

## 💡 중점적으로 봐주었으면 하는 부분

2022-08-06 17:00 UTC, syoung125 requested changes
1. 이부분이 input으로 구현되어있는데,
제가 이전에 구현했던 [ChatInput](https://62b83eaee7b099045d81e168-pishbqvsdu.chromatic.com/?path=/story/components-reusable-chatinput--%EC%84%A0%ED%83%9D%EB%90%9C-%EB%A3%B8%EC%9D%B4-%EC%9E%88%EB%8A%94-%EA%B2%BD%EC%9A%B0)  컴포넌트처럼 엔터 함에 따라 input 길이가 길어져야하고 maxHeight도 지정해야해서 이부분 input이 아닌 textarea로 수정해주셔야 할 것같습니다..!

2. 입력값이 없는 경우 전송버튼을 보여주지 않아야합니다!

2022-08-07 04:41 UTC, sooohka commented on src/components/reusable/Icon/Icon.tsx
> +      ${(p) => (p.colorname ? `fill: ${p.theme.color[colorname as ColorToken]} !important` : '')};
```
Warning: React does not recognize the `colorName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `colorname` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
왜나는진 모르겠지만 ㅋㅋㅋㅋ 위 에러입니다!!

2022-08-07 04:47 UTC, sooohka commented on src/components/room/RoomMemoForm/RoomMemoForm.tsx
> +          </button>
오 좋은점들 잘 집어주셨네요 ㅎㅎ 
좋은거 배우고갑니다~

2022-08-08 14:35 UTC, sooohka commented
> 



> 1. 이부분이 input으로 구현되어있는데,
>    제가 이전에 구현했던 [ChatInput](https://62b83eaee7b099045d81e168-pishbqvsdu.chromatic.com/?path=/story/components-reusable-chatinput--%EC%84%A0%ED%83%9D%EB%90%9C-%EB%A3%B8%EC%9D%B4-%EC%9E%88%EB%8A%94-%EA%B2%BD%EC%9A%B0)  컴포넌트처럼 엔터 함에 따라 input 길이가 길어져야하고 maxHeight도 지정해야해서 이부분 input이 아닌 textarea로 수정해주셔야 할 것같습니다..!
> 2. 입력값이 없는 경우 전송버튼을 보여주지 않아야합니다!

2b8c4ba2ee85fd7039e3dc8c459be642f1862188

2022-08-17 14:11 UTC, merged