feat: ✨ 메모룸 페이지 api 연동 (room CRUD)
memochat/memochat-client pull request #45
Opened 2022-10-26 03:13 UTC by syoung125

## 📍 주요 변경사항

1. 메모룸 페이지 api 연동 (room CRUD)
2. query key factory 도입 1d45ffb1491492158a1f6e01d03def3f6f6256cc
3. fulfill시 axios response data만 반환하도록 일괄 수정 ->  useQuery 사용시 data.data.data로 호출하는 구조 개선 489e92daab9f37de3dd62bb020e3023931e680e1

TODO: 
1. 메모 생성, 편집에 react hook form적용
2. 캐시 관련 option 공부 후 적용

## 🔗 참고자료

## 💡 중점적으로 봐주었으면 하는 부분

주요변경사항 중 2,3번을 중점적으로 봐주시면 좋을 것 같습니다!

2022-10-27 11:46 UTC, syoung125 commented on src/features/room/api/useMemoRoomCategoriesQuery.tsx
> +};
이렇게 반환해주어야 SSR에서 prefetch 시 JSON 파싱 관련 문제가 안생깁니다.
https://stackoverflow.com/questions/71763805/not-work-dehydrate-methodreact-query-in-nextjs

2022-10-27 14:25 UTC, sooohka commented on src/features/auth/api/useVerifications.tsx
> +  return res.data;
다 바꿔주셨군요!! 감사합니다~

2022-11-10 14:00 UTC, sooohka commented on src/features/auth/hooks/useAuth.tsx
> +      const { accessToken, refreshToken } = data;
깔끔하네요👍

2022-11-10 14:48 UTC, sooohka requested changes
작업량이 많으시네요. 고생하셨습니다!!
리뷰 확인해보시고 머지해주시면 좋을것 같아요!

2022-11-10 14:48 UTC, sooohka commented on src/features/room/api/useDeleteMemoRoomMutation.tsx
> +};
```suggestion
export const deleteMemoRoom = async ({ id }: { id: number }) => {
  const res = await axios.delete<DeleteMemoRooms['res']>(`/memo-rooms/${id}`);
  return res.data;
};

const useDeleteMemoRoomMutation = (
  options?: UseMutationOptions<DeleteMemoRooms['res'], unknown, { id: number }>,
) => {
  return useMutation({
    mutationFn: deleteMemoRoom,
    onSuccess: () => {
      queryClient.invalidateQueries(memoRoomKeys.list());
    },
    ...options,
  });
};
export default useDeleteMemoRoomMutation;
``` 
따로 화살표함수 쓰지말고 이런식으로 선언하는건 어떠신가요?

2022-11-10 14:48 UTC, sooohka commented on src/features/room/api/useMemoRoomCategoriesQuery.tsx
> +    staleTime: ONE_HOUR,
staleTime cacheTime이 들어간 이유가 궁금합니다.

2022-11-10 14:48 UTC, sooohka commented on src/features/room/api/useUpdateMemoRoomMutation.tsx
> +  );
```suggestion

export const updateMemoRoom = async ({
  id,
  param,
}: {
  id: number;
  param: UpdateMemoRooms['param'];
}) => {
  const res = await axios.put<UpdateMemoRooms['res']>(`/memo-rooms/${id}`, param);
  return res.data;
};

const useUpdateMemoRoomMutation = (
  options?: UseMutationOptions<
    UpdateMemoRooms['res'],
    unknown,
    { id: number; param: UpdateMemoRooms['param'] }
  >,
) =>
  useMutation({
    mutationFn: updateMemoRoom,
    onSuccess: () => {
      queryClient.invalidateQueries(memoRoomKeys.list());
    },
    ...options,
  });
```
위에 이유와 동일합니다!

2022-11-10 14:48 UTC, sooohka commented on src/features/room/components/RoomMemoForm/RoomMemoForm.tsx
> +    <S.Form onSubmit={handleSubmit((v) => onSubmit(v as RoomMemoFormType))}>
```suggestion
  const onSubmit: SubmitHandler<RoomMemoFormType> = (v) => {
    alert(JSON.stringify(v));
  };

  return (
    <S.Form onSubmit={handleSubmit(onSubmit)}>
```
이렇게 바꿔볼 수 있을것같아요

2022-11-10 14:48 UTC, sooohka commented on src/features/room/components/UpsertRoomDialog/UpsertRoomDialog.tsx
> +  const { mutate: updateRoom } = useUpdateMemoRoomMutation();
mutate 프로퍼티는 promise를 리턴하지 않아서 아래 await구문에 걸리지 않습니다!
mutateAsynce함수를 활용하거나 useQuery에 onSuccess 콜백을 넘겨줘야 할것 같아요

2022-11-10 14:48 UTC, sooohka commented on src/features/room/components/UpsertRoomDialog/UpsertRoomDialog.tsx
> +      await createMemoRoom(value);
mutate함수라 는 promise를 리턴하지 않습니다
<img width="633" alt="image" src="https://user-images.githubusercontent.com/67774824/201119387-31161236-7f73-437d-a2ab-d87b416a95e0.png">

2022-11-10 14:48 UTC, sooohka commented on src/features/room/components/UpsertRoomDialog/UpsertRoomDialog.tsx
>    }, [defaultValue]);
불필요한 useEffect인것 같습니다~
요부분 지우고 
```ts
  const [value, setValue] = useState<UpsertRoomDialogValue>(defaultValue | DEFAULT_VALUE);
```
이렇게 하시는건 어떠신가요?

2022-11-10 14:48 UTC, sooohka commented on src/features/room/components/UpsertRoomDialog/UpsertRoomDialog.tsx
> +  const clearValue = () => {
clear보다는 reset이란 네이밍이 어울리는것 같습니다!
clear는 뭔가 값을 다 지워버린다는 느낌이 더 강한것 같아요!

2022-11-13 03:49 UTC, syoung125 commented on src/pages/rooms/index.page.tsx
> +    router.push(`/rooms/${room.id}`);
RoomListItem 컴포넌트 내부를 보면 onClick에 대한 부가적 로직들이 들어가있어서 이 경우는 Link로 대체하기 힘들것 같습니다ㅠㅠ
<img width="460" alt="image" src="https://user-images.githubusercontent.com/39763891/201504703-a1d25597-6e5c-4e50-8d37-b8bb68b1d34c.png">

2022-11-13 03:52 UTC, syoung125 commented on src/features/user/api/useUsersMeQuery.ts
> +const useUsersMeQuery = (options?: UseQueryOptions<UsersMe['res'], unknown>) =>
넵ㅋㅋㅋ머지후 작업부탁드려요!

2022-11-13 04:14 UTC, syoung125 commented on src/pages/rooms/index.page.tsx
> +  const [selectedRoom, setSelectedRoom] = useState<MemoRoom | undefined>(rooms?.[0]);
[60bad66](https://github.com/memochat/memochat-client/pull/45/commits/60bad6678f4bf00f0de15352fe5a1502667e1060) 수정했습니다!

2022-11-13 04:16 UTC, syoung125 commented on src/features/room/hooks/useMemoForm.tsx
> +  props: Omit<UseFormProps<RoomMemoFormType>, 'resolver'> = { defaultValues },
엇 맞네요..!
defaultValue는 상단에서 할당해주는 것이 더 좋을 것같아서
[0dd6363](https://github.com/memochat/memochat-client/pull/45/commits/0dd6363964a17717cf22722f9a1e0930fb63d3f4) 이렇게 수정했습니다

2022-11-13 04:16 UTC, syoung125 commented on src/features/room/components/UpsertRoomDialog/UpsertRoomDialog.tsx
> +  const clearValue = () => {
react hook form 적용하면서 수정했습니다!
[f870c4d](https://github.com/memochat/memochat-client/pull/45/commits/f870c4ddd933eeca9676593bff528af885c09e6b)

2022-11-13 04:18 UTC, syoung125 commented on src/features/room/components/UpsertRoomDialog/UpsertRoomDialog.tsx
>    }, [defaultValue]);
react hook form 적용하면서 수정했습니다!
[f870c4d](https://github.com/memochat/memochat-client/pull/45/commits/f870c4ddd933eeca9676593bff528af885c09e6b)

2022-11-13 04:27 UTC, syoung125 commented on src/features/room/components/UpsertRoomDialog/UpsertRoomDialog.tsx
> +      await createMemoRoom(value);
헉 몰랐어요! 감사합니다
[b5fb3dc](https://github.com/memochat/memochat-client/pull/45/commits/b5fb3dc6db28cf474a40743bd5ad1c5ec719ca68) 수정완료

2022-11-13 04:27 UTC, syoung125 commented on src/features/room/components/UpsertRoomDialog/UpsertRoomDialog.tsx
> +  const { mutate: updateRoom } = useUpdateMemoRoomMutation();
[b5fb3dc](https://github.com/memochat/memochat-client/pull/45/commits/b5fb3dc6db28cf474a40743bd5ad1c5ec719ca68) 수정완료

2022-11-13 04:28 UTC, syoung125 commented on src/features/room/components/RoomMemoForm/RoomMemoForm.tsx
> +    <S.Form onSubmit={handleSubmit((v) => onSubmit(v as RoomMemoFormType))}>
요것도 react hook form 적용하면서 수정했습니다!
[f870c4d](https://github.com/memochat/memochat-client/pull/45/commits/f870c4ddd933eeca9676593bff528af885c09e6b)

2022-11-13 04:29 UTC, syoung125 commented on src/features/room/api/useDeleteMemoRoomMutation.tsx
> +};
react hook form 적용하면서 수정했습니다!
[f870c4d](https://github.com/memochat/memochat-client/pull/45/commits/f870c4ddd933eeca9676593bff528af885c09e6b)

2022-11-13 04:30 UTC, syoung125 commented on src/features/room/api/useMemoRoomCategoriesQuery.tsx
> +    staleTime: ONE_HOUR,
RoomCategory는 변경될 여지가 드물기 때문에, 
앱을 이용하는 동안은 최대한 룸카테고리에 대한 api 호출은 하지 않도록 하기 위함입니다!
(앱을 이용하는 동안 -> 1시간이라고 가정했어요)
나중에 로컬스토리지에 저장하도록 수정하면 필요없을 것같아요

2022-11-13 04:32 UTC, syoung125 commented on src/features/room/api/useUpdateMemoRoomMutation.tsx
> +  );
[f8b819d](https://github.com/memochat/memochat-client/pull/45/commits/f8b819d17169863a54f92cbe2b3584d0725bcce4) 수정했습니다 👍

2022-11-13 11:44 UTC, merged