Emotion Theming
memochat/memochat-client pull request #5
Opened 2022-07-16 08:42 UTC by sooohka

## 📍 주요 변경사항

Emotion Theme에 Typography 테마 추가

- Typography 테마가 추가됨에 따라 기존에 ColorTheme에만 정의되있던 테마를 상위폴더로 뺸뒤 각 속성(color, typography)별 테마를 spread연산자로 받아 최종 테마에 머지하는 형식으로 코드 구조 변경

- Typography 관련 속성 정의를 편하게 할 수 있는 mixin추가

## 🔗 참고자료

## 💡 중점적으로 봐주었으면 하는 부분

2022-07-16 20:14 UTC, syoung125 commented on src/themes/typography/theme.ts
> +  },
일괄 0이기 때문에 없어도 될것 같아용

2022-07-16 20:14 UTC, syoung125 commented on src/themes/typography/theme.ts
> +  },
<img width="406" alt="image" src="https://user-images.githubusercontent.com/39763891/179370426-c5c047ec-37ee-46b0-b5d6-a8e183ee0a72.png">

눌러보면 line-height가 픽셀값으로 적용되어있는데 참고해주세요!
(디자이너분께도 저값으로 설정해도 되는지 여쭤보려고 피그마 코멘트 남겼어요)

2022-07-16 20:14 UTC, syoung125 commented on src/themes/typography/types.ts
> +export type FontSizeType = { [T in GlobalTypographyGroup]: CSSObject['fontSize'] };
Record로 타입 지정하는 것은 어떤가요??
ex) `Record<GlobalTypographyGroup, CSSObject['fontSize']>` 

[참고 문서](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type)

2022-07-16 20:14 UTC, syoung125 commented on src/themes/typography/mixin.ts
> +const body6 = { ...parseTypographyTheme('body6') };
`{ ...parseTypographyTheme('h1') }`와 `parseTypographyTheme('h1')`는 같지 않나여?

요기서 spread 사용하신 이유가 있으신가요??

2022-07-16 20:14 UTC, syoung125 commented on src/themes/typography/mixin.ts
> +export { h1, h2, h3, h4, body1, body2, body3, body4, body5, body6 };
그리고 이 부분 globalTypographyGroupNames에 reduce 함수 사용하면
`const h1 = { ...parseTypographyTheme('h1') };`
이러한 패턴의 중복 코드는 줄일 수 있을 것같아요 :)

2022-07-16 20:19 UTC, syoung125 requested changes

2022-07-16 20:19 UTC, syoung125 commented on src/themes/typography/Typography.stories.tsx
> +    ${h4}
마지막으로 선언하신 font theme을 mixin에서 뽑아 사용하시는 이유가 있을까요??

1. emotion theme으로 넣어서 사용한다면 color사용하듯이  별도의 import 과정없이 `${({ theme }) => theme.font.h1};` 또는 `${({ theme }) => theme.typography.h1};`와 같은 형태로 사용할 수 있어서 구조가 통일된다는 장점이 있다고 생각해요
2. 타입 지정도 잘 되어있으면 `theme.typography.` 까지만 작성해도  vscode에서 사용가능한 폰트 타입 리스트가 나오니까 더 편할 것같아여

@woobottle 은 어떻게 생각하시나요??

2022-07-17 09:35 UTC, sooohka commented on src/themes/index.ts
> -  },
사실 새로 디자인 시스템을 만들어 가는 과정이라 생각해 피그마에 정의되지 않은 속성들은 뺴도 된다고 독자적으로 판단했던것 같네요 ㅜ 
이 부분 Pr에 내용 추가하도록 하겠습니다~

2022-07-17 09:41 UTC, sooohka commented on src/themes/typography/theme.ts
> +    body3: '',
넵 참고해서 적용할게요~

2022-07-17 09:43 UTC, sooohka commented on src/themes/typography/theme.ts
> +  },
제거할게요~

2022-07-17 09:47 UTC, sooohka commented on src/themes/typography/types.ts
> +export type FontSizeType = { [T in GlobalTypographyGroup]: CSSObject['fontSize'] };
오 이부분 안그래도 안쓰이는 T를 선언한거 같아 찝찝했는데 이런 방법이 있네요
이대로 수정할게요~

2022-07-17 09:49 UTC, sooohka commented on src/themes/typography/mixin.ts
> +const body6 = { ...parseTypographyTheme('body6') };
딱히 큰 이유는 없었던것 같아요. 뭔가 습관적으로 쓴것 같네요
수정하겠습니다~

2022-07-17 10:07 UTC, sooohka commented on src/themes/typography/Typography.stories.tsx
> +    ${h4}
저렇게 선언한건 사실 고정관념떄문이였던것 같아요. mixin을 보통 import해서 많이 쓰다보니까 ㅎㅎ
말씀하신대로 테마에서 import해서 쓰는편이 깔끔하고 가독성도 괜찮아질것 같네요

@woobottle  님 코멘트 남겨주시면 이어서 작업하겠습니다~

2022-07-17 10:30 UTC, sooohka commented on src/themes/index.ts
> -  },
시멘틱 칼라에 관해서는 정말 큰 변경점인거 매우 동의하고 다시 회의때 다같이 이야기 해봐도 좋을것 같아요~

2022-07-18 15:47 UTC, woobottle commented on src/themes/typography/Typography.stories.tsx
> +    ${h4}
우선 답변이 늦어서 죄송합니다. 
요새 정신이 많이 나가있네여.....

서영님의 방식대로 가는건 어떨까여??
수호님의 방식이 나쁜것이 아니라 이후의 개발 편의성에 더 좋지 않을까 싶은 생각이 드네여

우선 답변 늦어서 죄송합니다...
@sooohka @syoung125

2022-07-19 13:17 UTC, sooohka commented on src/themes/typography/Typography.stories.tsx
> +    ${h4}
넵 알겠습니다~ 그러면 서영님 코멘트 남겨주신대로 진행해볼게요

2022-07-19 15:37 UTC, sooohka commented
@syoung125  말씀 나눈대로 테마 변경해봤습니다. 보시고 문제 없으면 머지하겠습니다!

2022-07-20 14:25 UTC, syoung125 approved these changes
마지막 두개 pr 내용만 확인해주시고 반영하시면 바로 머지하셔도 됩니다!!
고생많으셨어요👍👍👍

2022-07-20 14:25 UTC, syoung125 commented on src/themes/color/types.ts
> +export type ColorTheme = ColorScheme;
ColorScheme 타입은 ColorTheme과 완전히 동일하네용
ColorScheme 타입은 없애도 될것같아요!

2022-07-20 14:25 UTC, syoung125 commented on src/themes/typography/theme.ts
> +};
typographyTheme내용과 typographyMixin이 동일한 내용인데
colorTheme과 구조 통일을 위해 colorTheme 선언한것처럼 여기에 믹신내용을 바로 적고, typographyMixin과 TypographyMixin 타입도 제거하는 것이 어떨까요??

2022-07-24 08:36 UTC, merged